### ISSUE TITLE
Benchmarking with interpolated type gives different results

### ISSUE THREAD

**Issue by rfourquet** [JuliaCI/BaseBenchmarks.jl#124]
Sorry for the unclear title. The problem can be summarized as follows: `T = UInt; run(tune!(@benchmarkable rand($T)))` gives a very over-estimated time compared to `run(tune!(@benchmarkable rand(UInt))`. While preparing a PR against julia/master, the RandomBenchmarks showed a lot of regressions because of this (in this case, `T` is set in a loop), even though the performance is not degraded when running individual benchmarks using the second form (i.e. using `UInt` directly). I tried solving this by using some incantation of `eval`, with no success. ~~My last try was something like `T=UInt; RD=RandomDevice(); g[...] = eval(@benchmarkable rand(Expr(:$, RD), $T)` (here `RD` must not be interpolated by `eval`, only by `@benchmarkable`). I'm not sure whether this works as intended~~(edit: it doesn't)~~, but it's ugly, so~~ wanted to discuss this problem here before working more on this.

**Comment by jrevels** [comment]
This behavior is intentional, but it seems to be too poorly documented in BenchmarkTools, because a lot of people run into this. 

In the former example, you're asking for the runtime of a function `f(UInt)` where `@noinline f(T) = rand(T)`. In the second example, you're asking for the performance of `f()` where `@noinline f() = rand(UInt)`. In other words, these benchmarks are measuring different things. The question becomes: What are you interested in measuring?

For example, the former might be considerably slower due to the compiler's choice of type argument specialization, i.e. `Datatype` vs. `Type{T}` (that may or may not be what's going on in your case).

**Comment by rfourquet** [comment]
Thanks for your answer. I understand the problem now, but was not aware of it when writing the random benchmarks. I had intended to measure the the second form (`f() = rand(UInt)`), which correspond to the performance which can be obtained by careful coding (i.e. using e.g. `f(::Type{T})` instead of `f(T::DataType)`). I think I have got a workaround to the difficulty I mentioned (of writing `@eval` around `@benchmarkable` with `$`) using a simple wrapper function. I will submit a PR soon for that.
