### ISSUE TITLE
Easier to use?

### ISSUE THREAD

**Issue by cormullion** [JuliaCI/BaseBenchmarks.jl#27]
(I wondered why this package wasn't registered.)

I found this tool difficult to install — in fact I haven't yet succeeded. It wants me to install Xcode (I'm on macOS) from the App store, which I don't really want to do.

But: I was looking for a simple way to measure the performance of Julia on two or three different machines  - a kind of `high-level score` that gives a number that can be used to compare their performance: i.e. Computer 1 scored 7.3, but Computer 2 scored 16.3. I know this will  be worrying vague and imprecise but it can be a useful first step in troubleshooting. 

So, is it possible to add something like an executive overview benchmark that's easy to run?

(Obviously I'd need to install it on all the machines I have first... :) )

**Comment by jrevels** [comment]
> (I wondered why this package wasn't registered.)

The package isn't registered because [rapid changes to our usage of this package in CI originally made settling on a versioning scheme kind of weird](https://github.com/JuliaCI/BaseBenchmarks.jl#which-version-of-basebenchmarks-is-being-used-in-ci). Now that the CI cycle is more routine and less experimental, we could switch to a more normal tag/release cycle, but there's not much benefit to doing that at the moment.

> I found this tool difficult to install — in fact I haven't yet succeeded. 

You can install unregistered packages using `Pkg.clone`; running `Pkg.clone("https://github.com/JuliaCI/BaseBenchmarks.jl")` in the Julia prompt should install this package without problems. Are you having trouble installing any other packages? 

The only external requirements can be found in the [REQUIRE file](https://github.com/JuliaCI/BaseBenchmarks.jl/blob/master/REQUIRE). As you can see, BaseBenchmarks doesn't have any direct binary dependencies. Note that on OSX, the Xcode command line utilities are a required dependency for many programs, including Julia itself.

> I was looking for a simple way to measure the performance of Julia on two or three different machines...is it possible to add something like an executive overview benchmark that's easy to run?

Every benchmark measures a slightly different thing; reducing many different benchmarks to a single metric can easily lead to misinterpreting performance. It's better to use [BenchmarkTools](https://github.com/JuliaCI/BenchmarkTools.jl) to automatically identify specific performance differences for you.

As for running this benchmarks in this package, you can use this code to run all of them (takes around 30 minutes to run all of them on my machine):

```julia
using BaseBenchmarks, BenchmarkTools
BaseBenchmarks.loadall!()
results = run(BaseBenchmarks.SUITE)
```

For more detailed guides, see the README in this repo, and the BenchmarkTools manual.

**Comment by cormullion** [comment]
@jrevels Thanks — fair enough! I'll install Xcode again and have another go. 

I'd still like to see something simple, like [Mathematica's](http://reference.wolfram.com/language/Benchmarking/ref/Benchmark.html), (takes about 10 seconds). Nobody's suggesting that these simple benchmarks are anything other than a rough guide, but they're useful for end-users to get a feel for relative performance of different hardware.

**Comment by jrevels** [comment]
Thanks for the link, the WolframMark benchmark would be great to implement in BaseBenchmarks at some point.

If you'd like a smaller benchmark suite that is closer to WolframMark (i.e. benchmarks based on real examples rather than microbenchmarks), you can run the `"example"` benchmarks:

```julia
run(BaseBenchmarks.SUITE[@tagged "example"])
```
