### ISSUE TITLE
`ExecutionResults not defined`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaCI/BaseBenchmarks.jl#9]
I have checked out the `nanosoldier` branch, and cloned Benchmarks and BenchmarkTrackers. When I try to load BaseBenchmarks I get this error:

```
ERROR: LoadError: LoadError: LoadError: UndefVarError: ExecutionResults not defined
 in include(::ASCIIString) at ./boot.jl:233
 in include_from_node1(::ASCIIString) at ./loading.jl:426
 in include(::ASCIIString) at ./boot.jl:233
 in include_from_node1(::ASCIIString) at ./loading.jl:426
 in eval(::Module, ::Any) at ./boot.jl:236
 [inlined code] from ./sysimg.jl:11
 in require(::Symbol) at ./loading.jl:357
 in include(::ASCIIString) at ./boot.jl:233
 in include_from_node1(::ASCIIString) at ./loading.jl:426
 in eval(::Module, ::Any) at ./boot.jl:236
 [inlined code] from ./sysimg.jl:11
 in require(::Symbol) at ./loading.jl:357
 in eval(::Module, ::Any) at ./boot.jl:236
while loading /home/jeff/.julia/v0.5/BenchmarkTrackers/src/metrics.jl, in expression starting on line 21
while loading /home/jeff/.julia/v0.5/BenchmarkTrackers/src/BenchmarkTrackers.jl, in expression starting on line 38
while loading /home/jeff/.julia/v0.5/BaseBenchmarks/src/BaseBenchmarks.jl, in expression starting on line 3
```

**Comment by jrevels** [comment]
The `nanosoldier` branch of BaseBenchmarks uses the [BenchmarkTools](https://github.com/JuliaCI/BenchmarkTools.jl) package, which is the impending replacement for my fork of Benchmarks + the BenchmarkTrackers package.

**Comment by JeffBezanson** [comment]
That's weird. I must have somehow gotten an old version of the nanosoldier branch.

**Comment by jrevels** [comment]
Sorry, it's probably pretty confusing right now for most people besides me - things are in an in-between state, since I'm gearing up for the imminent deployment of the new version of everything in lockstep, while simultaneously hot-patching over problems in the old system. 

The deployment of the new benchmarking framework has been waiting on a hardware reconfiguration of the cluster, which is finally scheduled to occur tomorrow. Assuming that goes as planned, all of these benchmarking packages will actually be registered with METADATA in a couple of days.
